### ISSUE TITLE
Activating PeasyMotion twice doesn't show up the same keys

### ISSUE THREAD

**Issue by isc30** [msomeone/PeasyMotion#1]
If you activate peasymotion, cancel and then activate again **without changing any code**, it doesn't show up the same shortcuts as before.
This makes the usage quite confusing since the brain tends to remember the old ones.

**Comment by msomeone** [comment]
Thanks for your feedback!
1) Between first and second activation is cursor position the same?
2) Which cancelation method do you use? ESC key? Arrows key? Something else?
3) Are you using VsVim or ViEmu plugins or any other that may affect cursor position?

**Comment by isc30** [comment]
I just noticed that it only happens when the cursor position is different, is there any reasoning for that?

**Comment by msomeone** [comment]
There is,
jump-labels are assigned using distance to cursor. Which is computed as abs(currentCursorPosition - jumpLabelPosition). This is done to assign "shortest"  labels  (if possible even "single" letter jumps) closer to current cursor position:

**[hj]** word1 **[hk]** word2 **[ha]** word3 **[hs]** word4
**[a]**word5 #word6 **[b]**word7 **[c]** word8
**[kl]** word9 **[kj]** word10 **[kh]** word11 **[kf]** word12
**[xx]** <- jump label
**#** - cursor
[a][b][c] - jump labels closest to cursor.

I may consider adding option to switch between current assignment logic and following one:
jump labels will be assigned consequently from top to bottom of visible text, ignoring current cursor position. Will this option help?

**Comment by isc30** [comment]
Yeah, multiple configuration options sound great, since the hard job is already done 😄 
I usually use this from vscode and it works great: [vscode-jumpy](https://marketplace.visualstudio.com/items?itemName=wmaurer.vscode-jumpy)

**Comment by msomeone** [comment]
Ok, gona add option for this

**Comment by msomeone** [comment]
Added an option to select jump label assignment algorithm (i think what you prefer may be approximated with 'ViewportRelative' mode).

You may also consider playing with caret sensitivity option and staying with CaretRelative algo. It will help with assigning shortest movements near caret position, while maintaining stable labels for small caret position changes.

Please let me know if it solved the issue.

Also improved performance significantly.

**Comment by isc30** [comment]
This sounds great!
Thanks
