### ISSUE TITLE
2 Char Search

### ISSUE THREAD

**Issue by CheesePizza100** [msomeone/PeasyMotion#12]
It would be nice to have the capability of 2 char search. The use case is to allow for a more targeted, precise search. Another benefit of this is fewer jump labels on the screen.  The search would search the entire file. This is the <Plug>(easymotion-s2) command.

Vim. Cursor is on line 5, first character. Invoke 2 char search for 'no':
![image](https://user-images.githubusercontent.com/1994230/81940088-cf263780-95bc-11ea-9112-7b9b602a71ff.png)

VsCodeVim. Cursor is on line 5, first character. Invoke 2 char search for 'no':
![image](https://user-images.githubusercontent.com/1994230/81940211-f846c800-95bc-11ea-982e-f0df4ee9417f.png)

**Comment by msomeone** [comment]
Glad to inform you that requested feature has been implemented! Feel free to grab new version via vsix gallery or from VS marketplace (auto-updates will work). Any feedback is welcomed as always :}

**Comment by CheesePizza100** [comment]
Works perfectly! Awesome!

**Comment by luoxz-ai** [comment]
Please support InvokePeasyMotionOneCharJump. Thank you.
