### ISSUE TITLE
What about InvokePeasyMotionTwoCharJumpTextSelect?

### ISSUE THREAD

**Issue by zstarkebaumcalico** [msomeone/PeasyMotion#16]
InvokePeasyMotionTwoCharJump is awesome, but there doesn't appear to be a complement for selecting text. I've tries to cheat it with marks, but its not quite as cool. I'm a vsvim user.

**Comment by msomeone** [comment]
Why not? Please, provide further details - should selection done till 2char position, include 2char position, or something else?
By the way i wonder if selection would be more convenient if whole line, containing jump label will be selected? Or should that be separate "line selection" mode?
