### ISSUE TITLE
Tools.InvokePeasyMotionLineJumpToWordBegining continues to capture input after the "jump position letter" has been entered.

### ISSUE THREAD

**Issue by johannesugb** [msomeone/PeasyMotion#17]
I have assigned `Alt + J`  to `Tools.InvokePeasyMotionLineJumpToWordBegining`.         
When go to a line and press the shortcut, several letters are presented. So far, so good.            
When I enter the "jump position letter", the cursor jumps to the right position but PeasyMotion continues to capture all further input in the status bar:

![image](https://user-images.githubusercontent.com/536330/90779324-f8faa300-e2fd-11ea-930c-4e9fabc9406f.png)

I would like to write in the editor, however, at the position where we have jumped to. I think, this is also the way it is intended to be, right?

This happens in Microsoft Visual Studio Community 2019, Version 16.6.2

**Comment by msomeone** [comment]
Thanks for reporting!
Would be nice to have more info about the issue, pleasy share a lil bit more info:
1) are there any extensions that might interact with input or focus in your MSVS instance. e.g. VsVim? ReSharper?
2) is this problem reproducible when using a different keyboard shortcut for 'line jump to word begining'?
3) is this problem reproducible with other PeasyMotion jump commands?

**Comment by johannesugb** [comment]
Thanks for looking into it.

ad 1.: Good point! It might happen only with ReSharper. I'll have to check again on the other PC, but on a PC without ReSharper installed, the problem does not happen.            
ad 2.: Yes
ad 3.: If I remember correctly, this also happened with other PeasyMotion jump commands (but I'll have to double check on the other PC)

**Comment by msomeone** [comment]
ok, thanks for the info!
please, let me know about `ad 1.`, so I will be able to reproduce and investigate the issue further.

**Comment by johannesugb** [comment]
Hmm, just tried again on the other PC and it does NOT happen anymore.       
I uninstalled PeasyMotion and reinstalled it. ReSharper is still active.            
I'll keep on testing and report if I encounter the problem again.

**Comment by msomeone** [comment]
Thanks! Will keep the issue opened then

**Comment by msomeone** [comment]
Plz, let me know if described behaviour will happen again. Thanks

**Comment by johannesugb** [comment]
I made a quick test and indeed, it appears that the problem is gone.
If it ever returns, I'll let you know!
