### ISSUE TITLE
Esc key not working

### ISSUE THREAD

**Issue by isc30** [msomeone/PeasyMotion#19]
After installing PeasyMotion, I noticed that `Esc` key doesn't work anymore as an shortcut to unselect text.
This happens after cancelling one selection using Esc.

**Comment by msomeone** [comment]
Thanks for reporting,
can you share which VS extensions are installed among PeasyMotion?

**Comment by isc30** [comment]
PeasyMotion is the only one. I noticed that this happens after a "failure" in PeasyMotion (usually due to clicking some dialog while typing). It seems like it never stops getting the keyboard handle at some point.
