### ISSUE TITLE
Sometimes the characters in the displayed box are cut off

### ISSUE THREAD

**Issue by ghost** [msomeone/PeasyMotion#2]
First of all - I want thank you for this extensions. I'm using it every day and it is great. 

And now bug. I noticed that some chars in box is little bit cut off. Below couple of examples. It looks like generated box is too small for fit all characters. Also i want suggest something that can be changed/upgraded. It will be nice if end user will have ability to change background and foreground colors of suggestion box. I'm using dark theme in VS.

![image](https://user-images.githubusercontent.com/271887/73606030-f628a280-45a5-11ea-9d96-e40d1ba1f7d3.png)
![image](https://user-images.githubusercontent.com/271887/73606035-06408200-45a6-11ea-880a-9b27c731052d.png)

**Comment by msomeone** [comment]
Thanks for reporting! Working on a fix.
I've opened new feature request, feel free to comment: https://github.com/msomeone/PeasyMotion/issues/3
Gona implement as soon as jump label box width issue will be fixed.

**Comment by msomeone** [comment]
Uploaded 1.0.24 version to the marketplace. Please update manually or download from VSIX Gallery.
Does it solve the issue?

Padding and formatting of jump label does not work correctly if viewport zoom (usually adjusted with mousewheel) is not equal to 100% (which is default).

**Comment by ghost** [comment]
Thank you for fixing it so fast. Everything is working as expected. Also I checked if chaning viewport zoom to diffrent values break anything. Everything was working fine.
