### ISSUE TITLE
How to do one char jump?

### ISSUE THREAD

**Issue by kgfly** [msomeone/PeasyMotion#20]
(Sorry if it's duplicate)

Similar to Tools.InvokePeasyMotionTwoCharJump, how to do one char jump?

Etc, I want to search one char. Then jump

Thanks.

**Comment by S0und** [comment]
As a concept i try to implement it, but it didn't turned out well. What i noticed that even TwoCharJump was an after though.

**Comment by luoxz-ai** [comment]
Please support InvokePeasyMotionOneCharJump. Thank you.

**Comment by msomeone** [comment]
Implemented in 1.9, please check official VS Gallery or update extension in Extension Manager. If installed manually from CI artifact, uninstall it first and install from Extension Manager.
