### ISSUE TITLE
BUG: PM changes document order in document tabs

### ISSUE THREAD

**Issue by gamagan** [msomeone/PeasyMotion#21]
Really great extension. I hope you find the time to work on it some more.

There's a bug that's kind of annoying: 
I have my document tabs along the left side of the screen, vertically. This is changed in (Tools>Environment>Tabs and Windows). The documents are sorted alphabetically. When I perform a 'jump to document tab' shortcut, PM reorders the titles of the documents. I don't mean that the documents shift from left-to-right... I mean that the alphabetical order in which they are listed changes. So, if you were focusing on document A, it will change to some document X. The order will then go back when either switching to the document or canceling via Escape.

Thanks for this really nice extension.

**Comment by msomeone** [comment]
I wonder whether the documents are sorted alphabetically with default VS settings?
As far as i remember, when i tested document tab jumps, documents were sorted in 'first opened' order. Is there an option to switch to non-alphabetically sorted order? Hope that helps. 
May be i can add an option to place jump labels at the end of document tab name for this particular case, as this will not mess the sorting order. But i`m not sure whether i will be able to fix this soon.
So if switching to other sorting mode workarounds the issue - please, let me know.

**Comment by gamagan** [comment]
Yes, it's possible to change to sorting order to Recently Opened First. But, that is its own problem because the .hpp/.cpp files are then not listed next to each other, which is more desirable than being able to jump with a shortcut to them.

**Comment by gamagan** [comment]
Just mentioning that I upgraded to MSVC 2022, and this issue is still present. Example:

![image](https://user-images.githubusercontent.com/9970152/159202409-bbb7c0b3-e9e0-4c04-ae0b-862937b70c58.png)

![image](https://user-images.githubusercontent.com/9970152/159202416-1ecdf070-5100-4fa7-bca0-23950e474418.png)

**Comment by msomeone** [comment]
Disable document tab sorting in VS options

**Comment by mivorobiev** [comment]
I`m sorry, but i have no idea how to fix this
