### ISSUE TITLE
Visual Studio 2022 support

### ISSUE THREAD

**Issue by redcoreit** [msomeone/PeasyMotion#24]
I wonder if the support of vs2022 is planned?!

This is an amazing extension and I will wait with the upgrade until this extension gets updated. If it is not planned then I have to find some replacement (not preferred) or to use an unofficial version (modify the `source.extension.vsixmanifest` file accordingly).

**Comment by msomeone** [comment]
It is somewhat 'planned' in the future, and unfortunately i do not have any release date.
Is there a fix you may share as PR? It would help a lot, as i am not able to make the fix and test it myself in coming weeks.
Any help or PR's are much appreciated. Thanks!

**Comment by redcoreit** [comment]
I've little to none experience in VS extension development but I will give it a shot.
We will see...

**Comment by redcoreit** [comment]
I managed to build a version that runs with VS2022, but I think it is more like a hack.
I will test this tomorrow during my daily work.

At least I googled the working version numbers for you :) 
#25

**Comment by redcoreit** [comment]
I had an [issue ](https://github.com/VsVim/VsVim/issues/2919) with VsVim that has been recently resolved.
I'm testing my modifications (couple of days) and it looks ok. No issue so far with VS2022 preview 3 and preview 4.

**Comment by dvygolov** [comment]
VS 2022 released but I won't use it until this awesome extension is there, no way!🙃

**Comment by CheesePizza100** [comment]
> VS 2022 released but I won't use it until this awesome extension is there, no way!🙃

I thought I was lost without ReSharper, I can't even code without this extension!

**Comment by dvygolov** [comment]
> I had an [issue ](https://github.com/VsVim/VsVim/issues/2919) with VsVim that has been recently resolved. I'm testing my modifications (couple of days) and it looks ok. No issue so far with VS2022 preview 3 and preview 4.

Can you please provide some info, what did you do to enable Visual Studio 2022 support?

**Comment by redcoreit** [comment]
I've downloaded the current nuget package, and I modified it according to my PR: https://github.com/msomeone/PeasyMotion/pull/25

Or just use my **UNOFFICIAL** package.
[PeasyMotion-preview-22.zip](https://github.com/msomeone/PeasyMotion/files/7578936/PeasyMotion-preview-22.zip)

**Comment by msomeone** [comment]
Apologize for delays. 
Lost access to marketplace. The most fast path to solve the issue - to upload unofficial package to marketplace as soon as i recover access.
In case it is not possible to upload separate version of extension for vs 2022.
Is it possible to modify #25 to include 16.0* versions also (package than should be able to install on vs2019 & vs2022)?
If its possible, CI will produce new artifact here - https://ci.appveyor.com/project/msomeone/peasymotion/history
and as soon as i have access to marketplace i will upload this package there and consider that as **official**.
Any thoughts?

**Comment by CheesePizza100** [comment]
If you are happy with the approach. Seems you are starting to get a dedicated base of users that are eager to use this in 2022.

**Comment by iabdelkareem** [comment]
Yes, please do this extension is a treasure.

**Comment by redcoreit** [comment]
I think it is possible, I will try it and I update the PR if it works.
@msomeone, in the meantime you can continue hacking the account :)

BRB

**Comment by kgfly** [comment]
VS2022 is a 64bit IDE while VS2019 is a 32bit IDE. Would it require more work because of the switch?

**Comment by mivorobiev** [comment]
That's right, there is more work to do, still experimenting with it on preview branch to provide simultaneous support for vs2019 & vs2022

**Comment by redcoreit** [comment]
Yeah, it is not trivial. I tried to solve the problem but I failed (yet).

I said that in theory it can be done, there are extensions that targets 2019 and 2022 as well:
https://marketplace.visualstudio.com/items?itemName=AlexanderGayko.ShowInlineErrors

But there are extensions that are separated by naming like VsVim 2022, VsVim 2019.

**Comment by mivorobiev** [comment]
Thanks for the link! Will investigate its vsix and look for extension's repo, maybe its opensource

**Comment by msomeone** [comment]
Done, have shared most stuff in "Shared C# project" by the book. Now we have vsix for 2019 and for 2022. Trying to upload on gallery. Stay tuned

**Comment by msomeone** [comment]
https://marketplace.visualstudio.com/items?itemName=maksim-vorobiev.PeasyMotion2022

https://marketplace.visualstudio.com/items?itemName=maksim-vorobiev.PeasyMotion

**Comment by hutterm** [comment]
I was trying this latest version for 2022 with the preview version of Visual Studio and it's been driving my Visual Studio installation into a "restart loop" ... something is going wrong there. It did let me install the extension without any issues (even tough it took considerably longer than any other extensions I have used)

Is this a known issue?

**Comment by msomeone** [comment]
@hutterm It is not a known issue. Might be starting in administrator mode and turning off extensions autoupdate + removing peasy motion (still in admin mode) + enable legacy/sync calls for extensions -> could help. Then try re-installing it from visual studio extension manager in VS.
