### ISSUE TITLE
visual studio 2022 support notification

### ISSUE THREAD

**Issue by ArnonHevlin** [msomeone/PeasyMotion#26]
after opening a visual studio solution, on the first use of a peasymotion action, I get the following notification:
"PeasyMotion: 2022 - visual studio 2022 support is here! Link is in 'more info' section" 
which can get annoying as I need to dismiss it each time.
could you make it so the notification only appears once, or add a way to suppress it?

**Comment by ArnonHevlin** [comment]
oddly enough the notification stopped popping up, not sure how to replicate this issue

**Comment by mivorobiev** [comment]
Please let me know if it happens again. might be 'dismissed' flag have not been saved properly
