### ISSUE TITLE
Feature request: please support InvokePeasyMotionOneCharJump

### ISSUE THREAD

**Issue by kgfly** [msomeone/PeasyMotion#27]
Please support InvokePeasyMotionOneCharJump. Thank you.

**Comment by luoxz-ai** [comment]
Please support InvokePeasyMotionOneCharJump. Thank you.

**Comment by panda7789** [comment]
Forked and created VSIX so you don't have to build it yourself.
https://github.com/panda7789/PeasyMotion

**Comment by msomeone** [comment]
@panda7789 , @kgfly we can grab builds of any branch of a main repo here - https://ci.appveyor.com/project/msomeone/peasymotion in 'Artifacts' section (both 2019 and 2022 VSIX available there). Btw if anyone wants to help with maintaining project, i`m glad to add that person as a maintainer.

**Comment by msomeone** [comment]
Implemented in 1.9, please check official VS Gallery or update extension in Extension Manager. If installed manually from CI artifact, uninstall it first and install from Extension Manager.

**Comment by msomeone** [comment]
Implemented in 1.9, please check official VS Gallery or update extension in Extension Manager. If installed manually from CI artifact, uninstall it first and install from Extension Manager.

**Comment by msomeone** [comment]
FYI: If old version keeps persisting - I had hard times myself with VS Extension Manager autoupdate. It kept reverting to 1.7.88 version for some reason. So I disabled extensions autoupdate and reinstalled manually from CI artifacts, ensured that version is 1.9*:
![image](https://github.com/msomeone/PeasyMotion/assets/783812/9557b442-7f2c-4177-9aec-aeab1603e5bc)
