### ISSUE TITLE
Tools.InvokePeasyMotionLineJumpToWordEnding puts cursor to the left of the last letter in the target word

### ISSUE THREAD

**Issue by NewlineCoding** [msomeone/PeasyMotion#28]
Tools.InvokePeasyMotionLineJumpToWordEnding puts cursor to the left of the last letter in the target word. The desired behavior for me is that the cursor is placed to the right of the last letter in the target word.

**Comment by msomeone** [comment]
Implemented in 1.9, please check official VS Gallery or update extension in Extension Manager. If installed manually from CI artifact, uninstall it first and install from Extension Manager.

**Comment by msomeone** [comment]
FYI: If old version keeps persisting - I had hard times myself with VS Extension Manager autoupdate. It kept reverting to 1.7.88 version for some reason. So I disabled extensions autoupdate and reinstalled manually from CI artifacts, ensured that version is 1.9*:
![image](https://github.com/msomeone/PeasyMotion/assets/783812/9557b442-7f2c-4177-9aec-aeab1603e5bc)
