### ISSUE TITLE
Add options to configure jump label visual style

### ISSUE THREAD

**Issue by msomeone** [msomeone/PeasyMotion#3]
For starters - background and foreground color selection.
* Save default style
* (A) Add option to manually override + color pickers
* (B) Add option to pick colors from visual studio theme.

Not sure if default style should be preserved. Maybe it is better to set (B) as default behaviour. But for now unsure which colors from theme to select as BG\FG colors. Maybe jump labels should have same style as selected text has (inverted colors)?

**Comment by ghost** [comment]
I think that it will be nice if I will have option to change default style (option A). VsVim probably works in similar way - there is predefined colors and I always can change color according to my needs.

**Comment by msomeone** [comment]
Finally implemented color settings.
Both options (A) and (B) are implemented. One can configure with live preview (just invoke PeasyMotion and go to Tools -> Options -> PeasyMotion. You can configure colors manually (default) or select any classification item (for example "Breakpoint" or "Selected text" to inherit colors from existing text editor classification items).

README & options descriptions were also updated.
Please let me know if it works as expected.

**Comment by ghost** [comment]
I was working with new version all day today. For me everything is working fine. I'm super pleased with option to setup my own colors. Thank you for this feature.

Also please note that on Market Place there is still version 1.0.31 for test i used version 1.0.34 but I downloaded it from your CI.

**Comment by msomeone** [comment]
Glad to hear :)
I`ll upload newest version, thanks for noticing!
