### ISSUE TITLE
Doesn't work in latest version of VS 2022

### ISSUE THREAD

**Issue by Shr4pNull** [msomeone/PeasyMotion#31]
After adding the extension and restarting VS there is no sign of it anywhere. No keyboard shortcut options, nothing.

**Comment by msomeone** [comment]
What version of visual studio are you using? Please enable syncronous extension loading:
![image](https://github.com/msomeone/PeasyMotion/assets/783812/30c4c318-4f00-4a4d-861a-33b0e6e18507)
