### ISSUE TITLE
Fake Jumps

### ISSUE THREAD

**Issue by gamagan** [msomeone/PeasyMotion#32]
Thanks for PeasyMotion. I think it is a fantastic extension.

It has one issue that is quite annoying. Make a selection, for example via Ctrl+W to select a word, and then invoke PeasyMotion -- the cursor will jump to the correct location; however, after immediately pressing an arrow function, the cursor will jump back to the previous location (where the selection was).

This happens to me, constantly. It's gotten to the point where I, subconsciously, don't invoke PeasyMotion jumps to avoid that fake jump.

Please, find it in your heart to fix that.

Thank you

**Comment by msomeone** [comment]
Hi, couple of question to help reproduce the bug:
1) do you use any Vim emulator extension? ViEmu or VsVim
2) do you perform any actions between Ctrl+w and peasymotiin invoke?
3) when word is selected using Ctrl+w , what peasymotion command you invoke?
4) visual studio version ? 2019 or 2022?
Thanks!

**Comment by gamagan** [comment]
Answers:

1. I did have it installed, but it was disabled. After I read your comment, I uninstalled it and tried it again. Issue still present.
2. No
3. Tools.InvokePeasyMotion
4. MSVC 2022 -- v17.9.6

Reproduce Steps:

1. Press Ctrl+W to select a word
2. Press keyboard shortcut assigned to Tools.InvokePeasyMotion
3. Type 2 letters to go to the target location
4. [caret will jump to target at this point]
5. Press any arrow key
6. [caret will jump back to location it was at (3)]

**Comment by msomeone** [comment]
Reproduced, looking for a fix

**Comment by msomeone** [comment]
Implemented in 1.9, please check official VS Gallery or update extension in Extension Manager. If installed manually from CI artifact, uninstall it first and install from Extension Manager.

**Comment by msomeone** [comment]
Implemented in 1.9, please check official VS Gallery or update extension in Extension Manager. If installed manually from CI artifact, uninstall it first and install from Extension Manager.

**Comment by msomeone** [comment]
FYI: If old version keeps persisting - I had hard times myself with VS Extension Manager autoupdate. It kept reverting to 1.7.88 version for some reason. So I disabled extensions autoupdate and reinstalled manually from CI artifacts, ensured that version is 1.9*:
![image](https://github.com/msomeone/PeasyMotion/assets/783812/9557b442-7f2c-4177-9aec-aeab1603e5bc)
