### ISSUE TITLE
Bugs with updated one char jump

### ISSUE THREAD

**Issue by gamagan** [msomeone/PeasyMotion#35]
Windows 10, MSVC 2022, v17.10 Preview 7

I don't use the one char jump (OCJ, Tools.InvokePeasyMotionOneCharJump) functionality, but gave it a try because of the new release (1.11). I found a couple of bugs with it.

A) OCJ  doesn't seem to be working at all. 

Reproduce:
 1. Press keyboard shortcut assign to the command
 2. Press key for character
 3. Once the labels come up, press the key for the label
 4. The labels disappears, but the cursor remains at the same location

B) OCJ locks up Visual Studio. 
 1. Press keyboard shortcut assign to the OCJ command
 2. Again, Press keyboard shortcut assign to the command
 3. PeasyMotion seems to enter an infinity loop

Regards,

**Comment by msomeone** [comment]
Thanks for reporting, fixed (A)
Regarding (B) - unable to  reproduce :(
