### ISSUE TITLE
Feature Request support for Arm64 (at least on Visual Studio 2022)

### ISSUE THREAD

**Issue by gorban** [msomeone/PeasyMotion#38]
The plugin doesn't appear in extension manager search, and it fails if you try to download the .vsix and install it. VsVim shows up though.

![image](https://github.com/msomeone/PeasyMotion/assets/1393236/aee1dc39-0ddd-4d52-9461-c37c916501fc)

Hardware specs:

------------------
System Information
------------------
      Time of this report: 6/20/2024, 21:27:07
             Machine name: <<omitted>>
               Machine Id: {<<omitted>>}
         Operating System: Windows 11 Home 64-bit (10.0, Build 26100) (26100.ge_release.240331-1435)
                 Language: English (Regional Setting: English)
      System Manufacturer: SAMSUNG ELECTRONICS CO., LTD.
             System Model: Galaxy Book4 Edge
                     BIOS: P00AKX.044.240615.WY.0940 (type: UEFI)
                Processor: Snapdragon(R) X Elite - X1E84100 - Qualcomm(R) Oryon(TM) CPU (12 CPUs), ~4.2GHz
                   Memory: 16384MB RAM
      Available OS Memory: 15974MB RAM
                Page File: 11038MB used, 21319MB available
              Windows Dir: C:\windows
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 192 DPI (200 percent)
       System DPI Setting: 192 DPI (200 percent)
          DWM DPI Scaling: UnKnown
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
 DirectX Database Version: 1.5.6
   Auto Super Res Version: 1.0.5.0
       System Mux Support: Mux Support Inactive - Ok
           Mux Target GPU: dGPU
           DxDiag Version: 10.00.26100.0712 64bit Unicode

------------
DxDiag Notes
------------
      Display Tab 1: No problems found.
        Sound Tab 1: No problems found.
        Sound Tab 2: No problems found.
          Input Tab: No problems found.

--------------------
DirectX Debug Levels
--------------------
Direct3D:    0/4 (retail)
DirectDraw:  0/4 (retail)
DirectInput: 0/5 (retail)
DirectMusic: 0/5 (retail)
DirectPlay:  0/9 (retail)
DirectSound: 0/5 (retail)
DirectShow:  0/6 (retail)

---------------
Display Devices
---------------
           Card name: Snapdragon(R) X Elite - X1E84100 - Qualcomm(R) Adreno(TM) GPU
        Manufacturer: Qualcomm Incorporated
           Chip type: Adreno 741
            DAC type: InternalDAC
         Device Type: Full Device (POST)
          Device Key: Enum\ACPI\VEN_QCOM&DEV_0C36&SUBSYS_CRD08380&REV_0087
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 7987 MB
    Dedicated Memory: 0 MB
       Shared Memory: 7987 MB
        Current Mode: 2880 x 1800 (32 bit) (60Hz)
         HDR Support: Supported
    Display Topology: Internal
 Display Color Space: DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
     Color Primaries: Red(0.679688,0.320312), Green(0.237305,0.722656), Blue(0.139648,0.049805), White Point(0.304688,0.321289)
   Display Luminance: Min Luminance = 0.004000, Max Luminance = 565.684998, MaxFullFrameLuminance = 400.000000
        Monitor Name: Samsung Monitor Device
       Monitor Model: unknown
          Monitor Id: SDC4188
         Native Mode: 2880 x 1800(p) (120.001Hz)
         Output Type: Internal
Monitor Capabilities: HDR Supported (BT2020RGB Eotf2084Supported )
Display Pixel Format: DISPLAYCONFIG_PIXELFORMAT_32BPP
      Advanced Color: AdvancedColorSupported 
      Using DDisplay: Yes
                 WCG: Wcg Not Supported
   Active Color Mode: DISPLAYCONFIG_ADVANCED_COLOR_MODE_SDR
         Driver Name: <>,C:\windows\System32\DriverStore\FileRepository\qcdx8380.inf_arm64_520e7769d20f1c04\qcdx11arm64xum.dll,C:\windows\System32\DriverStore\FileRepository\qcdx8380.inf_arm64_520e7769d20f1c04\qcdx11arm64xum.dll,C:\windows\System32\DriverStore\FileRepository\qcdx8380.inf_arm64_520e7769d20f1c04\qcdx12arm64xum.dll
 Driver File Version: 31.00.0054.0001 (English)
      Driver Version: 31.0.54.1
         DDI Version: 12
  Adapter Attributes: HARDWARE_TYPE_GPU,D3D11_GRAPHICS,D3D12_GRAPHICS,D3D12_CORE_COMPUTE,D3D12_GENERIC_ML,D3D12_GENERIC_MEDIA
      Feature Levels: 12_1,12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1,1_0_CORE
        Driver Model: WDDM 3.1
 Hardware Scheduling: DriverSupportState:AlwaysOff Enabled:False 
         Displayable: Supported 
 Graphics Preemption: DMA
  Compute Preemption: DMA
            Miracast: Not Supported by Graphics driver
      Detachable GPU: No
 Hybrid Graphics GPU: Integrated
     GPU Mux Support: None, Uninitialized - Unknown Error
      Power P-states: Not Supported
      Virtualization: Paravirtualization 
          Block List: No Blocks
  Catalog Attributes: Universal:True Declarative:True 
   Driver Attributes: Final Retail
    Driver Date/Size: 5/16/2024 8:00:00 PM, 17712000 bytes
         WHQL Logo'd: n/a
     WHQL Date Stamp: n/a
   Device Identifier: {9AF84DB1-0070-27FC-F231-4A1328C2D235}
           Vendor ID: 0x4D4F4351
           Device ID: 0x36334330
           SubSys ID: 0x30383338
         Revision ID: 0x0087
  Driver Strong Name: oem170.inf:e1a2240ea8ca58bb:QCDX_Inst_Base_150_X1E84100.NT:31.0.54.1:ACPI\VEN_QCOM&DEV_0C36&REV_0087
      Rank Of Driver: 00D12000
         Video Accel: 
         DXVA2 Modes: DXVA2_ModeH264_VLD_NoFGT  DXVA2_ModeHEVC_VLD_Main  DXVA2_ModeHEVC_VLD_Main10  DXVA2_ModeVP9_VLD_Profile0  DXVA2_ModeVP9_VLD_10bit_Profile2  {B8BE4CCB-CF53-46BA-8D59-D6B8A6DA5D2A}  {129F7B40-5C5B-48E5-8178-48C0CEA05A90}  {886348BD-B400-4378-A5AE-654ADC0947DC}  {4B3A8728-6585-4675-955E-D692AC71EE07}  {BDB6AC4F-8D9C-44F7-9731-52761C4924A9}  
         D3D12 Encode Modes: 
    Deinterlace Caps: {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                      {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBLineReplicate 
                      {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(UYVY,UYVY) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                      {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(UYVY,UYVY) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBLineReplicate 
                      {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(YV12,0x32315659) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                      {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(YV12,0x32315659) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBLineReplicate 
                      {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(NV12,0x3231564e) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                      {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(NV12,0x3231564e) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBLineReplicate 
                      {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC1,0x31434d49) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                      {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC1,0x31434d49) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBLineReplicate 
                      {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC2,0x32434d49) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                      {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC2,0x32434d49) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBLineReplicate 
                      {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC3,0x33434d49) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                      {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC3,0x33434d49) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBLineReplicate 
                      {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC4,0x34434d49) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                      {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC4,0x34434d49) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBLineReplicate 
                      {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(S340,0x30343353) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                      {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(S340,0x30343353) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBLineReplicate 
                      {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(S342,0x32343353) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                      {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(S342,0x32343353) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBLineReplicate 
        D3D9 Overlay: Not Supported
             DXVA-HD: Supported
        DDraw Status: Enabled
          D3D Status: Enabled
          AGP Status: Enabled
       MPO MaxPlanes: 9
            MPO Caps: VERTICAL_FLIP,HORIZONTAL_FLIP,RGB,YUV,STRETCH_YUV,STRETCH_RGB,HDR (MPO3)
         MPO Stretch: 20.000X - 0.250X
     MPO Media Hints: resizing, colorspace Conversion 
         MPO Formats: NV12
                          YCBCR_STUDIO_G22_LEFT_P601
                          YCBCR_FULL_G22_LEFT_P601
                          YCBCR_STUDIO_G22_LEFT_P709
                          YCBCR_FULL_G22_LEFT_P709
                          YCBCR_STUDIO_G22_LEFT_P2020
                          YCBCR_FULL_G22_LEFT_P2020
                          YCBCR_STUDIO_G22_TOPLEFT_P2020
                      P010
                          YCBCR_STUDIO_G22_LEFT_P601
                          YCBCR_FULL_G22_LEFT_P601
                          YCBCR_STUDIO_G22_LEFT_P709
                          YCBCR_FULL_G22_LEFT_P709
                          YCBCR_STUDIO_G22_LEFT_P2020
                          YCBCR_FULL_G22_LEFT_P2020
                          YCBCR_STUDIO_G22_TOPLEFT_P2020
                      R16G16B16A16_FLOAT
                          RGB_FULL_G10_NONE_P709
                      R8G8B8A8_UNORM
                          RGB_FULL_G22_NONE_P709
                          RGB_STUDIO_G22_NONE_P709
                          RGB_STUDIO_G22_NONE_P2020
                          RGB_FULL_G2084_NONE_P2020
                          RGB_STUDIO_G2084_NONE_P2020
                          RGB_FULL_G22_NONE_P2020
                          RGB_STUDIO_G24_NONE_P709
                          RGB_STUDIO_G24_NONE_P2020
                      B8G8R8A8_UNORM
                          RGB_FULL_G22_NONE_P709
                          RGB_STUDIO_G22_NONE_P709
                          RGB_STUDIO_G22_NONE_P2020
                          RGB_FULL_G2084_NONE_P2020
                          RGB_STUDIO_G2084_NONE_P2020
                          RGB_FULL_G22_NONE_P2020
                          RGB_STUDIO_G24_NONE_P709
                          RGB_STUDIO_G24_NONE_P2020
    PanelFitter Caps: VERTICAL_FLIP,HORIZONTAL_FLIP,RGB,YUV,STRETCH_YUV,STRETCH_RGB,HDR (MPO3)
 PanelFitter Stretch: 20.000X - 0.250X
   Extension Drivers: 
             Driver Name: C:\windows\System32\DriverStore\FileRepository\qcdxext_qcdpps8380.inf_arm64_900a4dce636524d5\qcdxext_qcdpps8380.inf
          Driver Version: 1.0.4010.3100
             Driver Date: 04/16/2024
         Driver Provider: Qualcomm Incorporated
      Catalog Attributes: Universal:False Declarative:True 
             Driver Name: C:\windows\System32\DriverStore\FileRepository\qcdxext_crd8380.inf_arm64_5c05f985a7ebe609\qcdxext_crd8380.inf
          Driver Version: 31.0.52.0
             Driver Date: 05/02/2024
         Driver Provider: Qualcomm Incorporated
      Catalog Attributes: Universal:False Declarative:True 
   Component Drivers: 
             Driver Name: Unknown
          Driver Version: Unknown
             Driver Date: Unknown
         Driver Provider: Unknown
      Catalog Attributes: N/A
             Driver Name: Unknown
          Driver Version: Unknown
             Driver Date: Unknown
         Driver Provider: Unknown
      Catalog Attributes: N/A

-------------
MCDM Devices
-------------
            Device Name: Snapdragon(R) X Elite - X1E84100 - Qualcomm(R) Hexagon(TM) NPU
    Device Manufacturer: Qualcomm Technologies, Inc.
          Hardware Type: NPU
     Adapter Attributes: D3D12_Generic_ML
Direct3D Feature Levels: n/a
           Engine Names: Compute
              Vendor ID: 0x4D4F4351
              Device ID: 0x41304430
           SubSystem ID: 0x00000000
            Revision ID: 0x0087
             Device Key: Enum\ACPI\QCOM0D0A
       Dedicated Memory: 0 MB
Dedicated System Memory: 0 MB
   Shared System Memory: 7987 MB
     Compute Preemption: DMA Buffer
            Driver Name: C:\windows\System32\DriverStore\FileRepository\qcnspmcdm8380.inf_arm64_39c71a2e8460c059\qcnspdx12arm64xum.dll,C:\windows\System32\DriverStore\FileRepository\qcnspmcdm8380.inf_arm64_39c71a2e8460c059\qcnspdx12arm64xum.dll,C:\windows\System32\DriverStore\FileRepository\qcnspmcdm8380.inf_arm64_39c71a2e8460c059\qcnspdx12arm64xum.dll,C:\windows\System32\DriverStore\FileRepository\qcnspmcdm8380.inf_arm64_39c71a2e8460c059\qcnspdx12arm64xum.dll
         Driver Version: 30.0.31.0
    Driver File Version: 30.00.0031.0000
   Driver Model Version: MCDM 3.0
       Driver File Size: 1113184 bytes
         Rank of Driver: 00FF0000
Driver Node Strong Name: oem39.inf:d051a8653d31e929:NSPMCDM_Device87.NT:30.0.31.0:ACPI\VEN_QCOM&DEV_0D0A&REV_0087
            Driver Date: 4/23/2024 20:00:00
      Driver Attributes: Final Retail
        Driver Language: English
            Driver Beta: Final
           Driver Debug: No
          Driver Signed: Yes
    Driver Signed Valid: Yes
               Hardware: Yes
             Detachable: No

-------------
Sound Devices
-------------
            Description: Speakers (Qualcomm(R) Aqstic(TM) Audio Adapter Device)
 Default Sound Playback: No
 Default Voice Playback: No
            Hardware ID: AUCD\VEN_SAMM&DEV_0851&SUBSYS_C1B9144D
        Manufacturer ID: N/A
             Product ID: N/A
                   Type: N/A
            Driver Name: qcaudminiport8380.sys
         Driver Version: 4487.150.0.0 (English)
      Driver Attributes: Final Retail
            WHQL Logo'd: n/a
          Date and Size: 4/3/2024 8:00:00 PM, 693696 bytes
            Other Files: 
        Driver Provider: Qualcomm Technologies, Inc.
         HW Accel Level: Emulation Only
              Cap Flags: 0x0
    Min/Max Sample Rate: 0, 0
Static/Strm HW Mix Bufs: 0, 0
 Static/Strm HW 3D Bufs: 0, 0
              HW Memory: 0
       Voice Management: No
 EAX(tm) 2.0 Listen/Src: No, No
   I3DL2(tm) Listen/Src: No, No
Sensaura(tm) ZoomFX(tm): No

**Comment by fobrs** [comment]
You need to add the following snippet to the manifest:
`
    <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[17.0, 18.0)">
    <ProductArchitecture>arm64</ProductArchitecture>
    </InstallationTarget>
`

**Comment by taze55** [comment]
I faced the same issue. This solution is necessary for me as well.

**Comment by msomeone** [comment]
@fobrs  Thanks for suggestion!

@gorban @taze55 
Feel free to test this build: https://ci.appveyor.com/project/msomeone/peasymotion/builds/50963415
I've uploaded v1.16 to marketplace also.

**Comment by taze55** [comment]
@msomeone 
Thank you, msomeone. I installed it from the marketplace and confirmed that it’s working correctly. It was a big help.
