### ISSUE TITLE
Line Motions/Jumping

### ISSUE THREAD

**Issue by CheesePizza100** [msomeone/PeasyMotion#5]
Use case: I am already on the line where I need to be, I need to navigate to a specific place within that line. This is a more targeted search. Say you have this text example below and that your cursor is at the beginning of the line:

This is some sample text for searching or finding in a sentence.

Let's say I wanted to get to the word "searching"
In Vim, you could do:
6w but counting words is not efficient.
f{s};;; also annoying because of the constant use of ;
/{wordToSearch} works but.....eh?

The result would be (letters in parentheses indicate jump point before or after word):

(a)This (b)is (c)some (d)sample (e)text (f)for (g)searching (h)or (i)finding (j)in (k)a (l)sentence. 

This(a) is(b) some(c) sample(d) text(e) for(f) searching(g) or(h) finding(i) in(j) a(k) sentence(l).

**Comment by msomeone** [comment]
Thanks for request! I'll let you know when it's ready.

**Comment by msomeone** [comment]
Sorry for the delay. Here is draft version:
http://vsixgallery.com/extension/PeasyMotion.a87d2837-6b54-4518-b014-3b29b4dcd902/

**Comment by CheesePizza100** [comment]
I did some quick testing with this line of text:

![image](https://user-images.githubusercontent.com/1994230/79254895-0cc36380-7e4b-11ea-8859-ff09344ab3b0.png)

// PeasyMotion
![image](https://user-images.githubusercontent.com/1994230/79255001-354b5d80-7e4b-11ea-9657-e51caf65b8c2.png)

// VSCode Vim EasyMotion
![image](https://user-images.githubusercontent.com/1994230/79255056-47c59700-7e4b-11ea-8c7b-2490cc1417b2.png)

// Vim EasyMotion
![image](https://user-images.githubusercontent.com/1994230/79255085-54e28600-7e4b-11ea-8914-b59ceafcc649.png)

Should this be consistent with the other flavors of EasyMotion? It looks like you are pretty close already.

**Comment by msomeone** [comment]
yeah, word search clearly needs a rewrite :)

**Comment by msomeone** [comment]
Test line should look like this now:
![image](https://user-images.githubusercontent.com/783812/79696871-f3297e00-8287-11ea-9aeb-8b10d5cbdd72.png)

You may consider trying test version here:
http://vsixgallery.com/extension/PeasyMotion.a87d2837-6b54-4518-b014-3b29b4dcd902/
If everything will work out fine, i`ll release on VS marketplace. ( just in case - use VS marketplace, it has autoupdate :} )

**Comment by CheesePizza100** [comment]
Tested it out and it works as expected, very nice!
