### ISSUE TITLE
Jump labels get too close to each other on brackets

### ISSUE THREAD

**Issue by msomeone** [msomeone/PeasyMotion#6]
Jump labels get too close to each other on brackets

**Comment by ghost** [comment]
Hello i want also confirm that this is happening. Screenshot below
![image](https://user-images.githubusercontent.com/271887/81661282-2f41a000-943c-11ea-94da-dde7efdd0c03.png)

Second row looks like `il` but acctualy it is `jl` so it is very confusing for me.

**Comment by msomeone** [comment]
Thanks for confirming! Working on a fix

**Comment by msomeone** [comment]
Solved, release will be available in store & for auto-update before end of week. feel free to grab experimental build on vsix gallery, but beware that auto-update wont work then, and new features are on the way :)

**Comment by ghost** [comment]
Thanks for fast fix. I will check latest fix it and let you know if it is ok.

**Comment by msomeone** [comment]
By the way, very curious whether you've tried a document tabs jump functionality?

**Comment by ghost** [comment]
Not yet but it sounds very promising. It definitely try it out.

**Comment by ghost** [comment]
Ok i found something else
![image](https://user-images.githubusercontent.com/271887/82138803-8623ec80-9823-11ea-8823-bd6eeb57ce42.png)
I marked on red two things that is not working fine.  In the first example `ffc` - first `f` is little bit on second `f`.  And for `jjn` something is also not working as expected - I pressed `j` and then I get something like this 
![image](https://user-images.githubusercontent.com/271887/82138898-3560c380-9824-11ea-8b6a-cb35e86ae2b3.png)
It is confusing that labels is changed to `mn` and there is still problem with overlapping letters.

**Comment by msomeone** [comment]
oh my :(
would you be so kind to share this particular piece of code with me, so i can reproduce this issue exactly? Thanks in advance. I mean only visible in screenshot  part of code, ofcourse

**Comment by ghost** [comment]
[TemperatureControllerTests.txt](https://github.com/msomeone/PeasyMotion/files/4639886/TemperatureControllerTests.txt)

Yes no problem - i attached file as txt.

**Comment by msomeone** [comment]
Thanks, working on it

**Comment by msomeone** [comment]
Which jump label assignment algo option do you use? CaretRelative, or ViewportRelative?

**Comment by msomeone** [comment]
Unfortunately i was not able to reproduce the issue using source code provided (with both jump algo options, btw it was broken, CaretRelative was used no matter what. fixed options serialization).
Here is what i get (modified source a lil, so y u i labels would appear on the same place as in your screenshot:
![tmp1](https://user-images.githubusercontent.com/783812/82144576-c600c900-984f-11ea-9f38-45e5cd6c6289.png)

Maybe there was some misunderstanding - the version with this fix was available on VSIX gallery only, not in the store. VSIX gallery address  - http://vsixgallery.com/extension/PeasyMotion.a87d2837-6b54-4518-b014-3b29b4dcd902/
Have you installed from store or from VSIX gallery?
The auto-updating version in VS store will be available before end of week. I can notify you.

In case you've used VSIX gallery latest version (as of writing it is 1.5.68) - and still experience overlapping jumplabels bug, please let me know if that would be appropriate to do one of the following:
a) install experimental plugin version ( i will enable jump label placement logging and we can try to to log into file instead of Debug/Trace WriteLine). Then i will be able to investigate your particular case, without trying to reproduce on my machine
b) provide  a lil bit more info: (PeasyMotion options screenshot),  visibile lines count in viewport (or range of visible lines, so i can match my viewport exatcly) and original file (not resaved/or smth) +or EOL convention info in your source file.

Thanks for taking time to help me fix the issue.

**Comment by ghost** [comment]
OK i found reason why it was working for me like this. I was using official version from store 1.4.61 for some reason this version if broken for me. I installed version from VSIX gallery and now everything is working as charm. Sorry for confusing and wasting of your time.

**Comment by msomeone** [comment]
no problem! glad it works now.  just be sure to grab official one from VS Store when it comes ready, so auto-updates will work again. or  i can email you to inform when its ready

**Comment by msomeone** [comment]
New version is available in VS marketplace.

**Comment by ghost** [comment]
Thanks!
