### ISSUE TITLE
Add Jump Labels to Beginning of Each Line

### ISSUE THREAD

**Issue by CheesePizza100** [msomeone/PeasyMotion#9]
Another EasyMotion feature to consider implementing: Adding jump labels to the beginning of each line.

Vim:
![image](https://user-images.githubusercontent.com/1994230/81311209-b82a9700-904a-11ea-89c6-4c8e362b118c.png)

VsCodeVim:
![image](https://user-images.githubusercontent.com/1994230/81311262-c973a380-904a-11ea-855e-bc1ba3b3359c.png)

There does appear to be a minor difference between the two. Vim EasyMotion adds a jump label to every line, regardless if it has text or not. VsCodeVim EasyMotion only adds jump labels to lines that have text. Don't have a strong preference either way.

Example text used in the screenshots:
Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book. 

I has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. 
It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently 
with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature 
from 45 BC making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, 
looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of 
the word in classical literature, discovered the undoubtable source. 
Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) 
by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The 
first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

**Comment by msomeone** [comment]
This feature has been added in 1.5.68 version.

**Comment by CheesePizza100** [comment]
This feature does work but I think I made a mistake defining what the expected behavior is. And I probably should have included another sample. When you have a file that is just straight text (like we see in the original screen shots posted above), there is no much difference.

Given this code snippet:
![image](https://user-images.githubusercontent.com/1994230/82270714-51a35400-993b-11ea-8454-94cc14420c95.png)

VsCode Vim EasyMotion behaves like this:
![image](https://user-images.githubusercontent.com/1994230/82270681-30426800-993b-11ea-87e7-82d219bed261.png)

Vim EasyMotion behaves like this:
![image](https://user-images.githubusercontent.com/1994230/82270767-73044000-993b-11ea-8f04-42c88f5cdb22.png)

IMO it makes more sense to give the user the option to jump to any line so target behavior should be like vanilla Vim EasyMotion.

For reference, here is PeasyMotion:
![image](https://user-images.githubusercontent.com/1994230/82271041-4997e400-993c-11ea-8f0b-298214435d94.png)

**Comment by msomeone** [comment]
fix peview available: https://www.vsixgallery.com/extension/PeasyMotion.a87d2837-6b54-4518-b014-3b29b4dcd902
